<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <EnableInterceptors>true</EnableInterceptors>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Auth.Core\Auth.Core.csproj" />
        <ProjectReference Include="..\Auth.Infrastructure\Auth.Infrastructure.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
        <PackageReference Include="Microsoft.Build.Tasks.Core" Version="18.7.1" />
        <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.7.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.4" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
