apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages-api
  template:
    metadata:
      labels:
        app: messages-api
    spec:
      containers:
        - name: messages
          image: ghcr.io/v-serghei/messages-api:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: messages-api
spec:
  selector:
    app: messages-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP