// <auto-generated />
namespace MovieNight.BusinessLogic.Migrations.Movie
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:MovieNight.BusinessLogic/Migrations/User/202405111107452_user.Designer.cs
    public sealed partial class user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user));
        
        string IMigrationMetadata.Id
        {
            get { return "202405111107452_user"; }
========
    public sealed partial class Movie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movie));
        
        string IMigrationMetadata.Id
        {
            get { return "202405141429495_Movie"; }
>>>>>>>> origin/edit_template:MovieNight.BusinessLogic/Migrations/Movie/202405141429495_Movie.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
