// <auto-generated />
namespace MovieNight.BusinessLogic.Migrations.User
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user));
        
        string IMigrationMetadata.Id
        {
            get { return "202405102105461_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
